### ISSUE TITLE
Crash with botan 1.11/2.0

### ISSUE THREAD

**Issue by felixonmars** [shadowsocks/libQtShadowsocks#104]
I have tried to use rc4-md5 which doesn't seem to use the botan pipe routine, and that seems to work flawlessly. The following crash happens immediately when sending packets with an aes-256-cfb mode.

Maybe relevant: https://marc.info/?l=botan-devel&m=145755126216465&w=2

```
terminate called after throwing an instance of 'Botan::Exception'
  what():  False assertion 'The nonce is fresh for this message' (expression m_fresh_nonce) in get @src/lib/filters/cipher_filter.cpp:49
Aborted (core dumped)
```

```
Dec 29 22:29:19 flygon.felixc.at systemd-coredump[8315]: Process 8114 (ss-qt5) of user 1000 dumped core.

                                                         Stack trace of thread 8268:
                                                         #0  0x00007f568885a04f raise (libc.so.6)
                                                         #1  0x00007f568885b47a abort (libc.so.6)
                                                         #2  0x00007f5688e6d4bd _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6)
                                                         #3  0x00007f5688e6b276 _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6)
                                                         #4  0x00007f5688e6b2c1 _ZSt9terminatev (libstdc++.so.6)
                                                         #5  0x00007f5688e6b4d8 __cxa_throw (libstdc++.so.6)
                                                         #6  0x00007f568bdcfbe4 _ZN5Botan17assertion_failureEPKcS1_S1_S1_i (libbotan-1.11.so.33)
                                                         #7  0x00007f568bbfe899 _ZN5Botan18Cipher_Mode_Filter11Nonce_State3getEv (libbotan-1.11.so.33)
                                                         #8  0x00007f568bbfe8b7 _ZN5Botan18Cipher_Mode_Filter9start_msgEv (libbotan-1.11.so.33)
                                                         #9  0x00007f568bc02252 _ZN5Botan6Filter7new_msgEv (libbotan-1.11.so.33)
                                                         #10 0x00007f568bc03cdb _ZN5Botan4Pipe9start_msgEv (libbotan-1.11.so.33)
                                                         #11 0x00007f568bc03f92 _ZN5Botan4Pipe11process_msgEPKhm (libbotan-1.11.so.33)
                                                         #12 0x00007f568c0b107d _ZN3QSS6Cipher6updateERK10QByteArray (libQtShadowsocks.so.1)
                                                         #13 0x00007f568c0be1d2 _ZN3QSS9Encryptor7encryptERK10QByteArray (libQtShadowsocks.so.1)
                                                         #14 0x00007f568c0c3561 _ZN3QSS8TcpRelay25onLocalTcpSocketReadyReadEv (libQtShadowsocks.so.1)
                                                         #15 0x00007f568941743e _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                                                         #16 0x00007f5689b9a125 n/a (libQt5Network.so.5)
                                                         #17 0x00007f5689b9a1dc n/a (libQt5Network.so.5)
                                                         #18 0x00007f5689ba4fe1 n/a (libQt5Network.so.5)
                                                         #19 0x00007f568a6b835c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                         #20 0x00007f568a6bfad1 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                                                         #21 0x00007f56893eb8e0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                         #22 0x00007f568944076d n/a (libQt5Core.so.5)
                                                         #23 0x00007f56857f2587 g_main_context_dispatch (libglib-2.0.so.0)
                                                         #24 0x00007f56857f27f0 n/a (libglib-2.0.so.0)
                                                         #25 0x00007f56857f289c g_main_context_iteration (libglib-2.0.so.0)
                                                         #26 0x00007f56894402bf _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                         #27 0x00007f56893e9d3a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                         #28 0x00007f568920c063 _ZN7QThread4execEv (libQt5Core.so.5)
                                                         #29 0x00007f5689210cf8 n/a (libQt5Core.so.5)
                                                         #30 0x00007f5688105454 start_thread (libpthread.so.0)
                                                         #31 0x00007f568890f7df __clone (libc.so.6)
```

**Comment by laxect** [comment]
same with it.
i'm under Arch linux and my botan is also the 1.11
```
terminate called after throwing an instance of 'Botan::Exception'
  what():  False assertion 'The nonce is fresh for this message' (expression m_fresh_nonce) in get @src/lib/filters/cipher_filter.cpp:49
[1]    3263 abort (core dumped)  ss-qt5

```

**Comment by Biggulu** [comment]
The same problem
terminate called after throwing an instance of 'Botan::Exception'
  what():  False assertion 'The nonce is fresh for this message' (expression m_fresh_nonce) in get @src/lib/filters/cipher_filter.cpp:49
[1]    2669 abort (core dumped)  ss-qt5

**Comment by librehat** [comment]
It seems botan 1.11 has changed something that breaks the compatibility. For the time being, I would suggest you to use botan 1.10 (I'm reluctant to change anything before 2.0 stable release)

**Comment by felixonmars** [comment]
Hrm, since we do not usually add old software to the repos, I will try to write a patch when I have some time...

**Comment by librehat** [comment]
Botan 1.11 is a development branch, which shouldn't be included in official repo in my opinion...

**Comment by felixonmars** [comment]
But for 1.10 branch, "... the developers do not recommend its use anymore." https://botan.randombit.net/#download

**Comment by librehat** [comment]
If they can't even freeze the API, I don't wish to waste time testing it. But they probably will release 2.0 sometime soon

**Comment by wolftankk** [comment]
same problem.

```
Could not find any algorithm named "RC2/CFB"
```

**Comment by laxect** [comment]
A simple solution is to install botan 1.10 and compile shadowsocks from
source.

**Comment by wolftankk** [comment]
I have found  libQtShadowsocks PKGBUILD and rebuild it. 

But in the official repo, it include libQtShadowsocks and shadowsocks-qt5, who can drop it ?

**Comment by laxect** [comment]
There is no botan 1.10 in offical repo. So drop it make no sense.

**Comment by ykelvis** [comment]
You can find the old PKGBUILD [here](https://github.com/archlinuxcn/repo/commit/428b4ffde743cdf05a5009022f4005ed6117514f) . And build it locally, then use `pacman -U` them.
It requires botan-1.10, which can be found in archlinuxcn repo.

**Comment by wolftankk** [comment]
shadowsocks-qt5:   https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=shadowsocks-qt5
libqtshadowsocks:  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libqtshadowsocks

I suggest recover them in AUR.

> You can find the old PKGBUILD here . And build it locally, then use pacman -U them.
It requires botan-1.10, which can be found in archlinuxcn repo.

**Comment by felixonmars** [comment]
After some tries I gave up as it seems too hard for C++ newbie like me :(

botan1.10 is now in [community] and libqtshadowsocks/shadowsocks-qt5 have been updated to depend on it instead.

**Comment by Artoria2e5** [comment]
Note: Botan 1.10 will hit EOL by the end of 2017.  Botan 2.0 has already been released.

**Comment by librehat** [comment]
We'll have to be careful to support both botan 1.10 and 2.0 (with some `#ifdef` macros). Since I'd be quite busy, I'll mark this as enhancement

**Comment by librehat** [comment]
It may be related to https://github.com/randombit/botan/issues/863 ? Can you try to build it with `-fstack-protector`? i.e. `qmake QMAKE_LFLAGS+="-fstack-protector" BOTAN_VER="2"`

**Comment by Artoria2e5** [comment]
Felix's mailing list link already explains why. Botan devs think that you shouldn't be reusing IVs, but that's what the stream-based SS protocol is doing anyway.

**Comment by librehat** [comment]
`botan 2.2.0` will contain the fix in the upstream, I'll make sure relevant changes are in place in `libQtShadowsocks` once botan is released
