### ISSUE TITLE
how to run shadowsocks-libqss as a proxy server and forward the TCP connection by IE setting

### ISSUE THREAD

**Issue by vincentruan** [shadowsocks/libQtShadowsocks#105]
hi, 
I have knew the awesome proxy tool from https://www.librehat.com/three-minutes-to-set-up-shadowsocks-server-on-windows/comment-page-1/#comment-46426, well, this comment was posted from me :).

I have a win PC, which can be connected to Internet by IE proxy script, another one can not be connected, but both of them are in one LAN, they can communicate by network, and yes, they can transfer data by shadowsocks.

The question is ,
without http proxy (IE), no one can be connected to Internet,  is there a good way to resolve it?

BR

**Comment by librehat** [comment]
I don't understand what your use case

**Comment by vincentruan** [comment]
okay

PC1( which one can connected internet with IE proxy setting)
PC2(which one can NOT connected, but both PC1 and PC2 are all in the same LAN)

with shadowsocks-libqss, I have built a proxy server in PC1, and also, PC2 can be connected to PC1 with shadowsocks-client.

the question is ,
shadowsocks-libqss can not accessed internet without IE proxy from PC1, how can I run it with IE setting, so that, PC2 can access internet indirectly?

**Comment by librehat** [comment]
I don't think you can do that unfortunately :(
