### ISSUE TITLE
QWebEngine with libQtShadowsocks in one process,then it continuously open the port

### ISSUE THREAD

**Issue by jefferyship** [shadowsocks/libQtShadowsocks#108]
QNetworkProxy::setApplicationProxy(proxy);

when i visit www.google.com.hk ,it could open thousand port ,and the QWebEngine is dead:
I assume it is because the proxy and the browser are caused in one process

 TCP    127.0.0.1:65506        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65507        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65508        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65509        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65510        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65511        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65512        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65513        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65514        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65515        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65516        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65517        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65518        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65519        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65520        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65521        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65522        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65523        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65524        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65525        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65526        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65527        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65528        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65529        127.0.0.1:1080         ESTABLISHED
 TCP    127.0.0.1:65530        127.0.0.1:1080         ESTABLISHED

**Comment by librehat** [comment]
This shouldn't be a problem. And I don't understand why QWebEngine would open so many ports for just one URL... You may wish to post some code snippet

**Comment by librehat** [comment]
Why did you close it?
