### ISSUE TITLE
关于libQtShadowsocks的若干安全性问题

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/libQtShadowsocks#109]
问题1：

以下内容节选自 https://breakwa11.blogspot.com/2016/09/shadowsocks.html

“针对原始协议，截止到本文发表前，在IV的部分实现有问题的分支为shadowsocks-python，libQtShadowsocks。首先它们的实现总是假设第一个TCP包一定能收到完整的IV，事实上如果第一个TCP包被拆开，那么会导致shadowsocks-python解密错误（使用了错误的IV）而断开连接，而libQtShadowsocks则直接整个服务端程序crash退出（数组越界断言）。在IV之后的协议头部分实现有问题的，除了shadowsocks-go是实现正确以外，其它分支（包括SSR）全都实现错误了，也就是说如果协议头部分的包如果被拆开，除了shadowsocks-go还能正常连接外，其它的全部都会断开连接。估计是最早的时候服务端某个分支是这么写的，然后其它分支都用相同的逻辑来写，导致全错了。“

问题2：

ss-libev最近移除了OTA，因为它不再能对抗GFW

那么如今的ss不使用OTA的情况下，是否会添加simple obfs功能，对抗干扰？

**Comment by librehat** [comment]
该文指出的问题已经在1.10 release中被修复

OTA被AEAD取代(见https://github.com/shadowsocks/shadowsocks-org/issues/30)，而对AEAD的支持需要Botan-2（等待上游修复一个carry over IV的regression bug）。

受我闲余时间限制，我目前只能在draft被广泛接受之后跟进实现，没有气力去做试验了。
