### ISSUE TITLE
请问怎么在内网映射出去？

### ISSUE THREAD

**Issue by jglimmers** [shadowsocks/libQtShadowsocks#115]
我有一台服务器，在内网，请问怎么配置config.json？我客户端直接连接IP+端口这样不行，监听不到。
![image](https://cloud.githubusercontent.com/assets/9823869/24230662/3021ad70-0fbb-11e7-86f6-a30fdc8f4911.png)

**Comment by jglimmers** [comment]
![image](https://cloud.githubusercontent.com/assets/9823869/24231179/e45c0c02-0fbd-11e7-9dec-d54658f6b7df.png)
![Uploading image.png…]()
因为速度比较好，所以想搭成ss

**Comment by librehat** [comment]
You should setup port forwarding yourself in the gateway/router
