### ISSUE TITLE
windows2016下服务端启动问题

### ISSUE THREAD

**Issue by now163** [shadowsocks/libQtShadowsocks#116]
config.json
{
"server":"0.0.0.0",
"server_port":8388,
"local_address":"127.0.0.1",
"local_port":1088,
"password":"cscushare",
"timeout":600,
"method":"rc4-md5",
"http_proxy": false,
"auth": false
}
启动时提示：
shadowsocks-libqss.exe -c config.json
Initialising ciphers...
RC4-MD5 (rc4-md5) initialised.
**Destination is not reachable. Please check your network and firewall settings. And make sure the profile is correct.**
Running in local mode.
TCP server listen at port 1088

外网连不上shadowsocks，防火墙已关闭。

**Comment by edgexie** [comment]
how to solve?

**Comment by now163** [comment]
@edgexie must add "-s" or "-S" parameter to running in server mode.

**Comment by Calvinfrog** [comment]
請問是怎麼解決的？
