### ISSUE TITLE
windows2016,500 Internal Privoxy Error

### ISSUE THREAD

**Issue by ZhongXiaoBei** [shadowsocks/libQtShadowsocks#117]
config.json：
{
"server":"0.0.0.0",
"server_port":8888,
"local_address":"127.0.0.1",
"local_port":1080,
"password":"1111111",
"timeout":600,
"method":"chacha20",
"http_proxy": false,
"auth": false
}
server cmd:
Initialising ciphers...
ChaCha (chacha20) initialised.
Running in server mode.
TCP server listen at port 8888

Client Browser：
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by xxlen** [comment]
我被这个问题困扰了1天,后来发现是防火墙的锅.  
把防火墙一关.. 我搭建的Python,  nodejs. 还有这个 都可以用了- -
