### ISSUE TITLE
The method  is not supported.

### ISSUE THREAD

**Issue by yansinwang** [shadowsocks/libQtShadowsocks#122]
#D:\shadowsocks>shadowsocks-libqss.exe
Initialising ciphers...
The method  is not supported.
Initialisation failed.
Controller is not valid. Maybe improper setup?

请问是什么原因？是不支持加密方式吗？config.json我的配置文件，环境是win10原版

{
    "server":"localhost",        //配置服务端地址，不需要修改
    "server_port":55623,           //服务端端口，可以根据需要修改，建议改成大点的不会被占用的端口
    "local_address":"127.0.0.1", //本地地址，不需要修改
    "local_port":1080,           //本地端口，可以根据需要修改
    "password":"321654987",         //密码
    "timeout":600,               //连接超时时间
    "method":"aes-256-cfb",          //加密方式
    "http_proxy": false,         //代理
    "auth": false                //需要验证
}

**Comment by librehat** [comment]
Strange... It looks fine to me

**Comment by librehat** [comment]
尝试去掉那些注释。看起来是json document parse失败了，所以method直接是空白
