### ISSUE TITLE
QT 编译链接子项目shadowsocks-libqss的链接错误LNK2019

### ISSUE THREAD

**Issue by zxbzswxr** [shadowsocks/libQtShadowsocks#125]
QtShadowsocks.lib(controller.obj):-1: error: LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static void __cdecl Botan::LibraryInitializer::initialize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?initialize@LibraryInitializer@Botan@@SAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "public: __cdecl QSS::Controller::Controller(bool,bool,class QObject *)" (??0Controller@QSS@@QEAA@_N0PEAVQObject@@@Z) 中被引用

之前已经把QtShadowsocks 库文件做好了，做第二个子项目shadowsocks-libqss在pro文件里加入了 

INCLUDEPATH     += D:/Qt/QTlianxi/libQtShadowsocks-master/lib \
                   C:/Botan/include/botan-2
LIBS            += -LC:/Botan/lib -lbotan
LIBS            += D:/Qt/QTlianxi/build-QtShadowsocks-Desktop_Qt_5_7_1_MSVC2015_64bit-Debug/lib/debug/QtShadowsocks.lib
但是链接不通过，总是LNK2019 错误，该怎么办

**Comment by librehat** [comment]
Botan-2 is properly supported yet

**Comment by librehat** [comment]
另外本项目现在使用cmake了，能否再尝试编译一下？很多qmake的古怪问题应该都解决了

**Comment by zxbzswxr** [comment]
@librehat  我试试 ，i will try ，hahahaah
