### ISSUE TITLE
coundn't work

### ISSUE THREAD

**Issue by Cyber-SiKu** [shadowsocks/libQtShadowsocks#127]
In ubuntu16.04.2 ss-qt5 :
ss-qt5: error while loading shared libraries: libQtShadowsocks.so.1: cannot open shared object file: No such file or directory

**Comment by zhoulifu** [comment]
Confirm this issue.

@Cyber-SiKu you could fix this issue by creating a symbol link `/usr/lib/libQtShadowsocks.so.1` to `/usr/lib/libQtShadowsocks.so` manually

**Comment by Cyber-SiKu** [comment]
@zhoulifu 3q

**Comment by WuShichao** [comment]
@zhoulifu Thx~

**Comment by librehat** [comment]
I've released a new build. Please just upgrade your system
