### ISSUE TITLE
 please help us to see    install libqtshadowsocks-dev

### ISSUE THREAD

**Issue by syncsuse** [shadowsocks/libQtShadowsocks#129]
error dpkg-buildpackage -uc -us -b  libqtshadowsocks- master    # please help us to see.

/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp: In destructor ‘virtual QSS::Cipher::~Cipher()’:
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:108:9: error: ‘kdf’ was not declared in this scope
     if (kdf)    delete kdf;
         ^~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:108:24: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
     if (kdf)    delete kdf;
                        ^~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:109:9: error: ‘msgAuthCode’ was not declared in this scope
     if (msgAuthCode)    delete msgAuthCode;
         ^~~~~~~~~~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:109:32: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
     if (msgAuthCode)    delete msgAuthCode;
                                ^~~~~~~~~~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:110:9: error: ‘msgHashFunc’ was not declared in this scope
     if (msgHashFunc)    delete msgHashFunc;
         ^~~~~~~~~~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:110:32: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
     if (msgHashFunc)    delete msgHashFunc;
                                ^~~~~~~~~~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp: In static member function ‘static bool QSS::Cipher::isSupported(const QByteArray&)’:
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:198:9: error: ‘unique_ptr’ is not a member of ‘std’
         std::unique_ptr<Botan::Keyed_Filter> filter;
         ^~~
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:198:44: error: expected primary-expression before ‘>’ token
         std::unique_ptr<Botan::Keyed_Filter> filter;
                                            ^
/home/suse/Downloads/libQtShadowsocks-master/lib/cipher.cpp:198:46: error: ‘filter’ was not declared in this scope
         std::unique_ptr<Botan::Keyed_Filter> filter;
                                              ^~~~~~
lib/CMakeFiles/QtShadowsocks.dir/build.make:137: recipe for target 'lib/CMakeFiles/QtShadowsocks.dir/cipher.cpp.o' failed
make[3]: *** [lib/CMakeFiles/QtShadowsocks.dir/cipher.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/suse/Downloads/libQtShadowsocks-master/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:89: recipe for target 'lib/CMakeFiles/QtShadowsocks.dir/all' failed
make[2]: *** [lib/CMakeFiles/QtShadowsocks.dir/all] Error 2
make[2]: Leaving directory '/home/suse/Downloads/libQtShadowsocks-master/obj-x86_64-linux-gnu'
Makefile:130: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/suse/Downloads/libQtShadowsocks-master/obj-x86_64-linux-gnu'
dh_auto_build: make -j4 returned exit code 2
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by mylxiaoyi** [comment]
maybe this will be helpful 

https://github.com/shadowsocks/libQtShadowsocks/pull/130

**Comment by mengfanyuc** [comment]
I also have this problem，so sad (ノへ￣、)

**Comment by librehat** [comment]
Master is also currently broken. Don't use master branch thanks
