### ISSUE TITLE
type std::out_of_range: map::at:  key not found

### ISSUE THREAD

**Issue by linfangrong** [shadowsocks/libQtShadowsocks#131]
libQtShadowsocks/lib/cipher.cpp   line 61
cipherInfo(cipherInfoMap.at(method))
method is QByteArray("AES-128/CFB")

it run error
terminating with uncaught exception of type std::out_of_range: map::at:  key not found

**Comment by librehat** [comment]
Which version you're running? The master is currently broken

**Comment by hosiet** [comment]
I can confirm this with 6514370e87d7ef91f5b84c32bf4912d09159f06f. Shadowsocks-qt5 would abort on new connection.

v1.11.0 seems okay.

**Comment by librehat** [comment]
Yes. The master is a wip branch and I'm aware of this issue... I'm currently refactoring many places
