### ISSUE TITLE
windows server 2016 datacenter/AWS VPS/运行时无反应

### ISSUE THREAD

**Issue by nullllunA** [shadowsocks/libQtShadowsocks#133]
运行bat后DOS窗口一直停在
TCP server listen at port 8388.

JSON文件就是从你的博客里面下载的，ip地址写的是0.0.0.0

如果我把JSON里面的SERVER IP地址改成这个VPS的公网IP，BAT文件闪了一下就没了。。。

**Comment by librehat** [comment]
那是正常的。或者请从cmd执行bat
