### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by chengliang833** [shadowsocks/libQtShadowsocks#138]
I sometimes need to check the log files. Can the server configure the path of the log file?

**Comment by librehat** [comment]
Are you using `shadowsocks-libqss`? If so, on Windows or Linux?

**Comment by librehat** [comment]
You can simply redirect all output to a log file if you wish so.
`shadowsocks-libqss.exe > logs 2>&1`

If you want syslog support on UNIX, it is currently not planned on application level. However, if your Qt has support for journald or syslogd, then you can force it to send logs to journald or syslogd by setting environment variable `QT_LOGGING_TO_CONSOLE` to `0`. See https://stackoverflow.com/questions/26295325/where-is-located-the-qdebug-qwarning-qcritical-and-qfatal-log-by-default-on-qt
