### ISSUE TITLE
Why I get v1.11.0 when building master

### ISSUE THREAD

**Issue by zyf0330** [shadowsocks/libQtShadowsocks#142]
I use master to build on Ubuntu according to doc, and get `libqtshadowsocks-dev_1.11.0-1_amd64.deb`.
How to get v2.0.0?

**Comment by yanwii** [comment]
use branch 'stable'.

**Comment by zanxj** [comment]
I also encountered the same problem, but I can't understand @yanwii said ,help me !
https://github.com/shadowsocks/shadowsocks-qt5/issues/597
