### ISSUE TITLE
编译错误 undefined reference to qMessageFormatString() 

### ISSUE THREAD

**Issue by leomatrix** [shadowsocks/libQtShadowsocks#144]
/usr/lib/x86_64-linux-gnu/libQt5Test.so.5.2.1: undefined reference to `qMessageFormatString(QtMsgType, QMessageLogContext const&, QString const&)'
collect2: error: ld returned 1 exit status

**Comment by librehat** [comment]
Qt 5.5 is required

**Comment by zzlthu** [comment]
I have installed the qt-opensource-linux-x64-5.5.1.run. and still error
Linking CXX executable address
/usr/lib/x86_64-linux-gnu/libQt5Test.so.5.2.1: undefined reference to `qMessageFormatString(QtMsgType, QMessageLogContext const&, QString const&)'

**Comment by librehat** [comment]
@zzlthu `libQt5Test.so.5.2.1:` Did you see the error string? The linker was still using Qt 5.2
