### ISSUE TITLE
打包时缺失某些东西?

### ISSUE THREAD

**Issue by HeroTch** [shadowsocks/libQtShadowsocks#145]
dh_install: Cannot find (any matches for) "usr/include/qtshadowsocks/*" (tried in ., debian/tmp)

dh_install: libqtshadowsocks-dev missing files: usr/include/qtshadowsocks/*
dh_install: missing files, aborting
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
这是怎么回事啊

**Comment by librehat** [comment]
Which version?

**Comment by librehat** [comment]
Btw, I will no longer provide `debian` folder in this project due to lacking of time maintaining the packages. I will also stop providing packages via PPA.
