### ISSUE TITLE
你好，windows服务的无法下载googleplay

### ISSUE THREAD

**Issue by firstnie** [shadowsocks/libQtShadowsocks#149]
libQtShadowsocks用windows做了服务端，无法下载Google play 市场应用，其他youtube等都正常，之前用CentOS 7 x64建立的服务端，可以下载，是windows哪里限制了吗？

**Comment by KnightSch** [comment]
据说，Google play 市场应用下载需要全局，因为它调用的是本地下载工具，可能不被代理。

**Comment by firstnie** [comment]
不是全局的问题，而是udp的问题。

**Comment by qian9008** [comment]
老早以前就反映过的问题了，断流

**Comment by librehat** [comment]
dupe. Check opened issue
