### ISSUE TITLE
你好老哥，win版的shadowsocks-libqss如何开启UDP？

### ISSUE THREAD

**Issue by dandzk** [shadowsocks/libQtShadowsocks#150]
你好，挺支持老哥你的shadowsocks-libqss项目，只不过编译后感觉像被阉割了一些功能，看过你博客网友也问过类似问题，我测试过在win下搭建ssr是可以开启udp的（需要python环境，不知是否与此有关），但是说明win系统是可以开启UDP的，请老哥抽空研究下，也算是有个突破，加油！

**Comment by dandzk** [comment]
win下搭建python版的ssr，需要Python库和openssl、git，这对于小鸡来说显得非常臃肿，而shadowsocks-libqss占内存低、轻巧，所以我最终选择了shadowsocks-libqss，尚若能解决UDP问题，或者说能把整个shadowsocks所有功能完美编译，那就是极好的，老哥，看你的了

**Comment by Etz-haChayim** [comment]
it's very good project

**Comment by librehat** [comment]
UDP应该是一直开启的，但是一直没有具体去测试。。。

**Comment by zhensss** [comment]
赞同！如果有UDP可选就好啦！

**Comment by zhensss** [comment]
有时间的话可以用sstap测试一下UDP的转发。
http://ss.7i.pw

**Comment by librehat** [comment]
#118

**Comment by dandzk** [comment]
我知道理论上shadowsocks源码是默认开启UDP的，但经过测试发现编译后的shadowsocks-libqss是并没开启，你可以使用sstap和SocksCap64来测试。
我也正是用这两款软件测试过的，我在同样的vps下搭建SSR后用这两款软件是可以测试通过UDP，但是，使用你的shadowsocks-libqss后，就测试不通过，所以这也是这么多人同求的原因。所以我前面说道有可能有些功能编译后出错了。老哥可使用这两款软件测试就明白了

**Comment by dandzk** [comment]
我这三段留言比较详细、细致，目的是为了给你测试提供参照   :） 老兄有时间是可以考虑继续完善你这个好作品的

**Comment by dandzk** [comment]
既然这么多人问，说明大家已经测试后不成功的了，就不要转发复制一些回答了，自己测试就明白用不了。还是那句话：实践出真知！
