### ISSUE TITLE
pls help compile QtShadowsocks.lib

### ISSUE THREAD

**Issue by sgww2** [shadowsocks/libQtShadowsocks#151]
Hello guys 

I have been trying to compile QtShadowsocks.lib for about several hours, however got some errors which I am not able to fix or understand. They are all about cipher.cpp

My system is win8 and Iam using QT Creator 4.4.4, might be somebody can help me with these. Thanks.

Here are the errors

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:153: error: C2440: 'reinterpret_cast': cannot convert from 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>' to 'const char *'

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:154: error: C2440: '<function-style-cast>': cannot convert from 'unsigned int' to 'std::string'

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:176: error: C2440: 'reinterpret_cast': cannot convert from 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>' to 'const char *'

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:176: error: C2440: '<function-style-cast>': cannot convert from 'unsigned int' to 'std::string'

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:192: error: C2440: 'reinterpret_cast': cannot convert from 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>' to 'const char *'

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\cipher.cpp:192: error: C2440: '<function-style-cast>': cannot convert from 'unsigned int' to 'std::string'

Also I have some warnings like

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\address.cpp:34: warning: C4273: 'QSS::Address::Address': inconsistent dll linkage

C:\QTProjects\libQtShadowsocks-2.0.0beta\lib\address.cpp:40: warning: C4273: 'QSS::Address::Address': inconsistent dll linkage

![qterror](https://user-images.githubusercontent.com/33878389/33093934-14bf3cd0-cf07-11e7-8097-4c1b4eebdae8.png)

**Comment by librehat** [comment]
I've given up maintaining the static library linking on windows. It seems very difficult with Cmake... I'd suggest you to build it dynamically

**Comment by sgww2** [comment]
Thank you for your answer :)
