### ISSUE TITLE
Hope to release a 2.0+ build

### ISSUE THREAD

**Issue by Etz-haChayim** [shadowsocks/libQtShadowsocks#155]
the last version of build is 1.10.0 .
I try to build the 2.0+ version but failed.....may be my environment of Qt5.5 is bad.
could u please release a v2.0+?
thank u!
it's a good project!

**Comment by librehat** [comment]
On Windows ? 

You need to make sure you've compiled all dependencies. I can update the wiki to include an example of how to compile it on Windows. I don't intend to provide binaries anymore

**Comment by Etz-haChayim** [comment]
yes on Windows10 with vs2017. I think I could try it again with the new wiki. thank u.

**Comment by librehat** [comment]
You can check it for reference https://github.com/shadowsocks/libQtShadowsocks/wiki/Compiling
