### ISSUE TITLE
shadowsocks-libqss 2.0.1 doesn't work in server mode

### ISSUE THREAD

**Issue by hexindent** [shadowsocks/libQtShadowsocks#161]
log:

v2.0.1

```
shadowsocks-libqss.exe -c config.json -S
2018-01-24 22:48:07.930 INFO: Initialising cipher: rc4-md5
2018-01-24 22:48:07.950 INFO: Running in server mode.
2018-01-24 22:48:10.520 DEBUG: Listen UDP socket state changed to QAbstractSocket::BoundState
2018-01-24 22:48:10.525 INFO: TCP server listening at ::1:8388
```

v1.10.0

```
shadowsocks-libqss.exe -c config.json -S
Initialising ciphers...
RC4-MD5 (rc4-md5) initialised.
Running in server mode.
TCP server listen at port 8388
```

`shadowsocks-libqss-v2.0.1-win64.7z` sha1sum: `60f0377a17181a37353c5a0349bd9debe48f03e5`
config.json file: https://github.com/shadowsocks/libQtShadowsocks/blob/master/shadowsocks-libqss/config.json
bat file: https://gist.github.com/librehat/c6a04effc8936ff93be5
Windows 7 x64 SP1
ShadowsocksX-NG 1.6.1

中文再补充几句：
按照 https://www.librehat.com/three-minutes-to-set-up-shadowsocks-server-on-windows/ 安装的软件，config里只改了密码。看到2.0.1有编译好的exe就赶紧更新了（技术不好还不会自己弄source code），但运行了之后并没有代理的效果，各种网站无法登陆，换回1.10.0覆盖再运行就好了，不知应该怎么解决？谢谢！

**Comment by librehat** [comment]
试试把localhost改成127.0.0.1看看？
看起来是在IPv6的local地址上监听了

**Comment by hexindent** [comment]
config.json的`"server":"localhost"`改成了`server":"127.0.0.1`

```
2018-01-25 7:33:43.165 INFO: Initialising cipher: rc4-md5
2018-01-25 7:33:43.168 INFO: Running in server mode.
2018-01-25 7:33:45.729 DEBUG: Listen UDP socket state changed to QAbstractSocket::BoundState
2018-01-25 7:33:45.733 INFO: TCP server listening at 127.0.0.1:8388
```
还是联网失败……

**Comment by hexindent** [comment]
@librehat 下载更新了v2.0.2，同样的问题还是存在，在config里改了"server": "127.0.0.1"也不能工作
#161

**Comment by librehat** [comment]
我有测试了用127.0.0.1是可以的。

**Comment by hexindent** [comment]
@librehat 又试了一次v2.0.2，ShadowsocksX-NG切了Auto Configure Mode和Global Mode，Safari也重启了，依旧不成功，换回v1.10.0了……那我再看看其他人的反馈吧，如果大家都用得没有问题，可能是我电脑出了什么情况

**Comment by DuneGemini** [comment]
我用v2.0.1和v2.0.2都可以使用安卓的影梭app连接服务器，但是梅林路由器的ss插件都无法正常连接墙外网站，不知是何缘故。。

**Comment by hexindent** [comment]
@librehat 终于改好了，看了 #156 的配置，发现`"server"`可以写外网IP，之前只试了localhost和127.0.0.1，都不工作。`"server":"localhost"`改成`"server":"144.***.***.***"`，其余不变，客户端就可以使用服务器代理了。
