### ISSUE TITLE
Get trouble in configuring my server

### ISSUE THREAD

**Issue by darkness-y** [shadowsocks/libQtShadowsocks#162]
我的服务器跑在一个路由后面，路由有公网ip。我在路由端静态配置了服务器的ip，并做了端口映射。
在服务器端配置了对应的内网ip地址和内部映射端口。
我的client是mac下的ShadowsocksX-NG，配置了路由的公网ip和对应的外部映射端口。

运行服务后，可以看到connecting xxxx from xxxx
但始终没有返回，safari里也一直是等待，直到最后超时。url和直接的ip地址都是这样。

不知道问题出在哪里，麻烦能不能指点一下，感谢！

**Comment by librehat** [comment]
There is a bug in 2.0.1 #161

**Comment by darkness-y** [comment]
Could u pls provide a compiled .exe of this bug-fix version? Thank you so much!

**Comment by librehat** [comment]
@darkness-y Just uploaded
