### ISSUE TITLE
使用最新版本发现问题，服务端能接收到客户端的连接但是客户端始终无法访问网络

### ISSUE THREAD

**Issue by ZhongXiaoBei** [shadowsocks/libQtShadowsocks#163]
![image](https://user-images.githubusercontent.com/15073931/35421400-fd931d7e-027d-11e8-9481-1b6ebc23ad04.png)

**Comment by mavk** [comment]
metoo，系统windows server 2016，换v1.10.0就可以。

**Comment by idowant** [comment]
我也是这样，也是windows server 2016

**Comment by ZhongXiaoBei** [comment]
@mavk  v1.10.0会不会出现运行一段时间后就不行的情况？

**Comment by librehat** [comment]
Confirmed #161

**Comment by mavk** [comment]
@ZhongXiaoBei 不会出现
