### ISSUE TITLE
AEAD data chunk is incomplete

### ISSUE THREAD

**Issue by mylxiaoyi** [shadowsocks/libQtShadowsocks#165]
在Debian Stretch下使用shadowsocks-qt5时会在终端看到大量如下输出：

> AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for length)
Remote: Integrity failure: ChaCha20Poly1305 tag check failed

操作系统Debian Stretch，编译器GCC6，libQtShadowsocks为最新的master分支，
可成功编译，但是运行后会看到大量如上的输出，因而无法下载稍大的文件。

网络环境为河北移动。

这是libQtShadowsocks的问题还是所用的botan2的问题呢？

谢谢。

**Comment by librehat** [comment]
"AEAD data chunk is incomplete" is an expected output in real world use. They're not errors and it simply means that it's waiting for more data hence you can safely ignore them.

What do you mean that you cannot download big files? Any stable reproducible procedures?

**Comment by testcaoy7** [comment]
同样的问题。不仅无法下大文件，浏览网页也常常断掉。用shadowsocks-windows做客户端就没有这样的问题。

服务器端：ss-libev （git commit f2ccc5d）

**Comment by mylxiaoyi** [comment]
@testcaoy7

还以为我遇到的问题只是个例呢😊
我也发现在windows和Android下似乎是正常的。

**Comment by mylxiaoyi** [comment]
@librehat 

I use Firefox 59.0.2 (64bit)+SwitchOmega under Debian 9 Stretch when I download some file directly from the browser,  it always failed.

I set up my own server and installed ss-libev with AES-256-CFB crypt method, and it works fine.
maybe it is the problem of CHACHA20-IETF-POLY1305. when I use CHACHA20-IETF-POLY1305, I have the same problem.

**Comment by bringtree** [comment]
广东 电信。第一个访问可以连 第二个就崩

**Comment by KaraRyougi** [comment]
Same issue here. Environment is Kubuntu 18.04 and qtShadowsocks.
The error log goes like this:

```
AEAD data chunk is incomplete (too small for payload)
AEAD data chunk is incomplete (too small for payload)
(a lot of repeated errors)
AEAD data chunk is incomplete (too small for length)
Remote: Integrity failure: ChaCha20Poly1305 tag check failed
```

Not able to download anything large. Can confirm not a network issue since Mac, Android and Windows devices running Shadowsocks all work fine.

**Comment by bringtree** [comment]
@KaraRyougi I use another ss( librehat / shadowsocks. ). it can run. but it will spell many flow. At the end, I use the docker to deal with these question. the ss images can be found easily.  
![image](https://user-images.githubusercontent.com/20106478/41716374-d1b556da-7588-11e8-957d-9dc09945b8f7.png)

**Comment by KaraRyougi** [comment]
@bringtree I switched to shadowsocks-libev...

**Comment by ttimasdf** [comment]
+1 on this. Use ss-qt5 on single-threaded download tool will more likely get in trouble. e.g. Downloading software from Ubuntu Software Store (using snap).

**Comment by ttimasdf** [comment]
如果有人和我一样从ss-qt5转出来的话，建议 Linux 下用 SS 搭配 v2ray 会比单纯 shadowsocks-libev 的体验要好很多很多。包括内建HTTP代理、chnroute、systemd开机启动等等。用[官方一键脚本](https://www.v2ray.com/chapter_00/install.html#linuxscript)安装后，填好这个配置文件里的ss连接信息，放在 `/etc/v2ray/config.json` 即可。HTTP代理位于本机端口1085。想要socks和http共存的话，也可以参见官方文档，加几行就行。
```json
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": 1085,
    "protocol": "http",
    "settings": {}
  },
  "outbound": {
    "protocol": "shadowsocks",
    "settings": {
      "servers": [
        {
          "address": "your.ss.hostname",
          "port": 23333,
          "method": "chacha20-ietf-poly1305",
          "password": "your-ss-password",
          "level": 0
        }
      ]
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPOnDemand",
      "rules": [
        {
          "type": "field",
          "outboundTag": "direct",
          "domain": ["geosite:cn"]
        },
        {
          "type": "chinaip",
          "outboundTag": "direct",
          "ip": ["geoip:cn"]
        }
      ]
    }
  }
}
```
