### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by wlmnzf** [shadowsocks/libQtShadowsocks#167]
/usr/bin/ld: CMakeFiles/ss-qt5.dir/ssvalidator.cpp.o: undefined reference to symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4_@@GLIBCXX_3.4.21'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/ss-qt5.dir/build.make:622: recipe for target 'src/ss-qt5' failed
make[2]: *** [src/ss-qt5] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/ss-qt5.dir/all' failed
make[1]: *** [src/CMakeFiles/ss-qt5.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by librehat** [comment]
Are you using `master` branch? I couldn't reproduce this error. More inputs are welcomed

**Comment by jianbosu** [comment]
i use the release 2.02 win64
