### ISSUE TITLE
 No package 'botan-1.10' found windows

### ISSUE THREAD

**Issue by sgww2** [shadowsocks/libQtShadowsocks#171]
Hi guys

Really struggled with the botan. Here is the cmake log

`Running Windows Runtime device detection.
C:/Qt/5.9.3/winrt_armv7_msvc2015/bin/winrtrunner.exe --list-devices
Found 2 Windows Runtime devices.
Running "C:\Program Files\CMake\bin\cmake.exe -E server "--pipe=\\.\pipe\{e2eed112-885e-45bb-b99d-bd1f74affa31}" --experimental" in C:\libQtShadowsocks-2.0.2\build.
Starting to parse CMake project for Qt Creator.
Checking for module 'botan-1.10'
  No package 'botan-1.10' found
CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:28 (pkg_check_modules)

Configuring incomplete, errors occurred!
See also "C:/libQtShadowsocks-2.0.2/build/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.`

Could somebody please explain why it is not find while it was installed according instruction https://botan.randombit.net/manual/building.html I also added C:\botan in th PATH env variable.

Where I should install botan in order cmake will able to find this.

And if I used DUSE_BOTAN2=ON as a cmake argument why it told me about botan 1.10 

![image](https://user-images.githubusercontent.com/33878389/36795076-b96ba9d0-1caa-11e8-8a41-85c8c7d9739a.png)

Thanks in advance

**Comment by gallimaufrystew** [comment]
pkgconfig /path/to/pkgconfig

**Comment by librehat** [comment]
As above, you need to change PKG_CONFIG_PATH variable for pkg-config to find your botan

**Comment by sgww2** [comment]
Thank you for the reply, but that doesn't work.

 I have  botan installed in C:\Botan-2.4.0 and doing the following

`master@DESKTOP-CKFBKC2 MINGW32 /c/Botan-2.4.0
$ make install
/usr/bin/python ./src/scripts/install.py --prefix=/mingw64 --build-dir="build" --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
   INFO: Botan 2.4.0 installation complete

master@DESKTOP-CKFBKC2 MINGW32 /c/Botan-2.4.0
$ ls /c/Botan-2.4.0
botan.exe  Botan-2.4.0.tar  botan-test.exe  build  configure.py  doc  libbotan-2.a  license.txt  Makefile  news.rst  readme.rst  src  version.txt

master@DESKTOP-CKFBKC2 MINGW32 /c/Botan-2.4.0
$ echo $PKG_CONFIG_PATH
/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig:/c/Botan-2.4.0/:/c/Botan-2.4.0

master@DESKTOP-CKFBKC2 MINGW32 /c/Botan-2.4.0
$ cd /c/SH/libQtShadowsocks-2.0.2/

master@DESKTOP-CKFBKC2 MINGW32 /c/SH/libQtShadowsocks-2.0.2
$ cd build/

master@DESKTOP-CKFBKC2 MINGW32 /c/SH/libQtShadowsocks-2.0.2/build
$ cmake -G "MSYS Makefiles" .. -DUSE_BOTAN2=ON -DCMAKE_INSTALL_PREFIX=/mingw64
-- Checking for module 'botan-2>=2.3.0'
--   No package 'botan-2' found
CMake Error at C:/msys32/mingw32/share/cmake-3.10/Modules/FindPkgConfig.cmake:420 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/msys32/mingw32/share/cmake-3.10/Modules/FindPkgConfig.cmake:598 (_pkg_check_modules_internal)
  CMakeLists.txt:26 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "C:/SH/libQtShadowsocks-2.0.2/build/CMakeFiles/CMakeOutput.log".`

Where I made a mistake? Thanks

**Comment by sgww2** [comment]
I understand what was wrong, need to add /c/Botan-2.4.0/build path to PKG_CONFIG_PATH
$ echo $PKG_CONFIG_PATH
/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig:/c/Botan-2.4.0/:/c/Botan-2.4.0:/c/Botan-2.4.0/build

However now a new challenge occurs 

master@DESKTOP-CKFBKC2 MINGW32 /c/SH/libQtShadowsocks-2.0.2/build
$ cmake -G "MSYS Makefiles" .. -DUSE_BOTAN2=ON -DCMAKE_INSTALL_PREFIX=/mingw64
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BOTAN_LIBRARY_VAR
    linked by target "QtShadowsocks" in directory C:/SH/libQtShadowsocks-2.0.2/lib

-- Configuring incomplete, errors occurred!
See also "C:/SH/libQtShadowsocks-2.0.2/build/CMakeFiles/CMakeOutput.log".

**Comment by sgww2** [comment]
Every step is a challenge ... why the hell this shity cmake does not want to find botan with find_library

From CMakeLists

find_library(BOTAN_LIBRARY_VAR
             NAMES botan botan-1.11 botan-2
             HINTS "/mingw/bin" "/mingw/lib" "/mingw/include" "/mingw/include/botan-1.10" "/mingw/include/botan-2" "/mingw/include/botan-1.10/botan" "/mingw/include/botan-2/botan")

botan is installed successfully and present, but still

master@DESKTOP-CKFBKC2 MINGW32 /c/SH/libQtShadowsocks-2.0.2/build
$ cmake -G "MSYS Makefiles" .. -DCMAKE_INSTALL_PREFIX=/mingw64
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BOTAN_LIBRARY_VAR
    linked by target "QtShadowsocks" in directory C:/SH/libQtShadowsocks-2.0.2/lib

**Comment by sgww2** [comment]
I used mingw64 instead of mingw32 and the previous issue has gone. Again another problem during make stage 

master@DESKTOP-CKFBKC2 MINGW64 /c/SH/libQtShadowsocks-2.0.2/build
$ cmake -G "MSYS Makefiles" .. -DUSE_BOTAN2=ON -DCMAKE_INSTALL_PREFIX=/mingw64
-- Configuring done
-- Generating done
-- Build files have been written to: C:/SH/libQtShadowsocks-2.0.2/build

master@DESKTOP-CKFBKC2 MINGW64 /c/SH/libQtShadowsocks-2.0.2/build
$ make -j4
Scanning dependencies of target QtShadowsocks_autogen
[  3%] Automatic MOC for target QtShadowsocks
[  3%] Built target QtShadowsocks_autogen
Scanning dependencies of target QtShadowsocks
[  6%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/address.cpp.obj
[  9%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/addresstester.cpp.obj
[ 12%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/chacha.cpp.obj
[ 15%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/cipher.cpp.obj
/C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp: In function ‘void {anonymous}::chacha_quarter_round(uint32_t&, uint32_t&, uint32_t&, uint32_t&)’:
/C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:38:42: warning: ‘T Botan::rotate_left(T, std::size_t) [with T = unsigned int; std::size_t = unsigned int]’ is deprecated: Use rotl<N> or rotl_var [-Wdeprecated-declarations]
     a += b; d ^= a; d = rotate_left(d, 16);
                                          ^
In file included from /mingw64/include/botan-2/botan/bswap.h:13:0,
                 from /mingw64/include/botan-2/botan/loadstor.h:13,
                 from /C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:25:
/mingw64/include/botan-2/botan/rotate.h:88:10: note: declared here
 inline T rotate_left(T input, size_t rot)
          ^~~~~~~~~~~
/C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:39:42: warning: ‘T Botan::rotate_left(T, std::size_t) [with T = unsigned int; std::size_t = unsigned int]’ is deprecated: Use rotl<N> or rotl_var [-Wdeprecated-declarations]
     c += d; b ^= c; b = rotate_left(b, 12);
                                          ^
In file included from /mingw64/include/botan-2/botan/bswap.h:13:0,
                 from /mingw64/include/botan-2/botan/loadstor.h:13,
                 from /C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:25:
/mingw64/include/botan-2/botan/rotate.h:88:10: note: declared here
 inline T rotate_left(T input, size_t rot)
          ^~~~~~~~~~~
/C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:40:41: warning: ‘T Botan::rotate_left(T, std::size_t) [with T = unsigned int; std::size_t = unsigned int]’ is deprecated: Use rotl<N> or rotl_var [-Wdeprecated-declarations]
     a += b; d ^= a; d = rotate_left(d, 8);
                                         ^
In file included from /mingw64/include/botan-2/botan/bswap.h:13:0,
                 from /mingw64/include/botan-2/botan/loadstor.h:13,
                 from /C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:25:
/mingw64/include/botan-2/botan/rotate.h:88:10: note: declared here
 inline T rotate_left(T input, size_t rot)
          ^~~~~~~~~~~
/C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:41:41: warning: ‘T Botan::rotate_left(T, std::size_t) [with T = unsigned int; std::size_t = unsigned int]’ is deprecated: Use rotl<N> or rotl_var [-Wdeprecated-declarations]
     c += d; b ^= c; b = rotate_left(b, 7);
                                         ^
In file included from /mingw64/include/botan-2/botan/bswap.h:13:0,
                 from /mingw64/include/botan-2/botan/loadstor.h:13,
                 from /C/SH/libQtShadowsocks-2.0.2/lib/chacha.cpp:25:
/mingw64/include/botan-2/botan/rotate.h:88:10: note: declared here
 inline T rotate_left(T input, size_t rot)
          ^~~~~~~~~~~
[ 18%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/common.cpp.obj
[ 21%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/controller.cpp.obj
[ 25%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/encryptor.cpp.obj
[ 28%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/rc4.cpp.obj
[ 31%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/tcprelay.cpp.obj
[ 34%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/udprelay.cpp.obj
[ 37%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/httpproxy.cpp.obj
[ 40%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/socketstream.cpp.obj
[ 43%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/tcpserver.cpp.obj
[ 46%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/profile.cpp.obj
make[2]: *** No rule to make target 'C:/Windows/System32/botan.lib', needed by 'lib/libQtShadowsocks.dll'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object lib/CMakeFiles/QtShadowsocks.dir/QtShadowsocks_autogen/mocs_compilation.cpp.obj
make[1]: *** [CMakeFiles/Makefile2:87: lib/CMakeFiles/QtShadowsocks.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
