### ISSUE TITLE
这个版本是不是不支持混淆?

### ISSUE THREAD

**Issue by Easy10010** [shadowsocks/libQtShadowsocks#173]
>     "timeout": 300,
>     "method": "chacha20",
>     "http_proxy": false,
>     "protocol": "auth_aes128_sha1",
>     "protocolparam": "",
>     "obfs": "tls1.2_ticket_auth",
>     "obfsparam": ""

客户端改成相应的混淆参数后, 客户端无法连接,服务端显示`Can’t parse header: wrong encryption method or password?`  
客户端把协议改成`origin`, 混淆改成`plain`, 就可以连上了  
这个版本是不是不支持混淆?

**Comment by Winyer** [comment]
你居然还能启动，我填入`    "protocol": "origin",
    "protocolparam": "",
    "obfs": "plain",
    "obfsparam": ""`后直接闪退，程序都启动不了

**Comment by Winyer** [comment]
突然才看到这是SS，不是SSR。。。
