### ISSUE TITLE
请问可以增加一个参数，设置输出的log-level吗？

### ISSUE THREAD

**Issue by saobee** [shadowsocks/libQtShadowsocks#174]
目前只有一个 D 选项，输出debug级别，我想尽量关闭所有的输出。
我的版本：x64 2.0.2，运行在一台win2008的服务器上。

我运行的server端输出大量的info 和debug信息，尤其是在运行时间超过设置的timeout之后，会有大量的info级别日志输出，占用CPU。

希望能自定义输出级别，我希望程序就安稳(安静)长期的运行。

**Comment by librehat** [comment]
Currently `-D` is broken and fixed in the master. I will add a parameter to set the logging level in a better way
