### ISSUE TITLE
windows server 2016上的SS服务端端口问题

### ISSUE THREAD

**Issue by KurodaAk1ra** [shadowsocks/libQtShadowsocks#180]
SS服务端端口用443和80段都得时候运行正常，但是一旦换其他的端口后，客户端连接时完全没反应了，服务器上已经设置了出站入站规则，关了防火墙，但是依旧不好用，443和80用来弄网站了，想重新开一个端口给SS用，请问有什么解决办法么，谢谢大佬们了

**Comment by librehat** [comment]
Unrelated
