### ISSUE TITLE
compilation error on ubuntu 16.04

### ISSUE THREAD

**Issue by admzzz** [shadowsocks/libQtShadowsocks#181]
[ 59%] Built target qss_test_autogen
Scanning dependencies of target qss_test
[ 62%] Building CXX object test/CMakeFiles/qss_test.dir/main.cpp.o
[ 65%] Building CXX object test/CMakeFiles/qss_test.dir/address.t.cpp.o
[ 68%] Building CXX object test/CMakeFiles/qss_test.dir/chacha.t.cpp.o
/home/admz/build/libQtShadowsocks-stable/test/main.cpp:1:10: fatal error: QTest: No such file or directory
 #include <QTest>
          ^~~~~~~
compilation terminated.
[ 71%] Building CXX object shadowsocks-libqss/CMakeFiles/shadowsocks-libqss.dir/client.cpp.o
In file included from /home/admz/build/libQtShadowsocks-stable/test/chacha.t.cpp:1:
/home/admz/build/libQtShadowsocks-stable/test/chacha.t.h:3:10: fatal error: QtTest: No such file or directory
 #include <QtTest>
          ^~~~~~~~
compilation terminated.
test/CMakeFiles/qss_test.dir/build.make:62: recipe for target 'test/CMakeFiles/qss_test.dir/main.cpp.o' failed
make[2]: *** [test/CMakeFiles/qss_test.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
test/CMakeFiles/qss_test.dir/build.make:88: recipe for target 'test/CMakeFiles/qss_test.dir/chacha.t.cpp.o' failed
make[2]: *** [test/CMakeFiles/qss_test.dir/chacha.t.cpp.o] Error 1
[ 75%] Building CXX object shadowsocks-libqss/CMakeFiles/shadowsocks-libqss.dir/main.cpp.o
[ 78%] Building CXX object shadowsocks-libqss/CMakeFiles/shadowsocks-libqss.dir/utils.cpp.o
In file included from /home/admz/build/libQtShadowsocks-stable/test/address.t.cpp:1:
/home/admz/build/libQtShadowsocks-stable/test/address.t.h:29:10: fatal error: QtTest: No such file or directory
 #include <QtTest>
          ^~~~~~~~
compilation terminated.
test/CMakeFiles/qss_test.dir/build.make:75: recipe for target 'test/CMakeFiles/qss_test.dir/address.t.cpp.o' failed
make[2]: *** [test/CMakeFiles/qss_test.dir/address.t.cpp.o] Error 1
CMakeFiles/Makefile2:264: recipe for target 'test/CMakeFiles/qss_test.dir/all' failed
make[1]: *** [test/CMakeFiles/qss_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object shadowsocks-libqss/CMakeFiles/shadowsocks-libqss.dir/shadowsocks-libqss_autogen/mocs_compilation.cpp.o
[ 84%] Linking CXX executable shadowsocks-libqss
[ 84%] Built target shadowsocks-libqss
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by admzzz** [comment]
workaround:
because 
_option(USE_BOTAN2 "Build ${PROJECT_NAME} with Botan-2" ON)_
in CMakeList.txt does not work, i'd added a foolish if $-)

if (USE_BOTAN2)
    add_definitions(-DUSE_BOTAN2)
    pkg_check_modules(BOTAN REQUIRED botan-2>=2.3.0)
else()
    add_definitions(-DUSE_BOTAN2)
    pkg_check_modules(BOTAN REQUIRED botan-2>=2.3.0)
endif()

and after that it compiles ok.

**Comment by librehat** [comment]
You need Qt Test module:
QtTest: No such file or directory
