### ISSUE TITLE
让在美国的朋友用自己的电脑部署好了 我在国内用不了啊 是哪里有问题吗

### ISSUE THREAD

**Issue by x7883751** [shadowsocks/libQtShadowsocks#199]

**Comment by zhensss** [comment]
检查一下你美国朋友公网ip....

再看看你配置，是否能直接ping通。

**Comment by x7883751** [comment]
> 检查一下你美国朋友公网ip....
> 
> 再看看你配置，是否能直接ping通。

能直接ping通，我用google cloud测试也用不了，不知道自己是哪里出错了，那个服务器地址填的是外网ip吗？能否留个联系方式请教一下，微信之类的？
