### ISSUE TITLE
Possible memory leak in server mode on Windows

### ISSUE THREAD

**Issue by ctexlive** [shadowsocks/libQtShadowsocks#21]
shadowsocks-libqss-v1.6.1-win64 于win7 x64下做服务端。
客户端用qt5或者其他，浏览普通网页没问题，但下载iso或者其他大文档时，大概下到300MB的时候就会中断，观察服务端任务管理器，发现进程突然消失然后又启动。
如果把服务端换成python版的就没有一点问题。

以下只测试了win环境
shadowsocks-libqss-v1.6.1-win64的优点：初始内存占用小。
缺点：相比python版，它不稳定，CPU占用率显著高于python版，而且下载大文件时，它读写硬盘较大。
python版性能最好，而且非常稳定，CPU占用率也很低。同等条件下下载大文件，libqss CPU >20%,python版 ~10%.  
硬件条件：AMD athlon II X2 250 ，win7 x64， 100M局域网

**Comment by librehat** [comment]
进程突然消失又启动？服务端有任何错误日志输出吗？

**Comment by ctexlive** [comment]
刚仔细观察了下，发现并非是后端服务消失又启动，因为debug界面没有变化，而是任务进程里消失又出现。
现象：客户端下载1.2G的iso，服务端任务管理观察，发现shadowsocks-libqss的内存占用和客户端下载的大小同步增长，当增长到 x00 MB（此时客户端也正好下载了x00 MB），服务进程就挂了。我猜测shadowsocks-libqss把下载的数据统统缓存到内存里，导致内存溢出而挂掉。普通上网每次下载最多也就几MB大小，不会影响它。

**Comment by librehat** [comment]
shadowsocks只是一个代理而已，它哪来的「下载数据」这一说呢，是浏览器在下载，shadowsocks收到一点数据就会处理完发送掉，连接过期就会销毁。Linux下的内存占用没有异常（0.4%左右），你说的这个现象倒是像内存泄漏了，所有的内存都没有得到正常释放的感觉。

请问就是普通上网的话，shadowsocks-libqss的内存占用也会一直稳步上升么？

**Comment by librehat** [comment]
撤回之前说的，在Linux下无法重现，服务一直稳定运行，内存占用一直是0.4%（2G RAM的ARM板子）。

如图下载了快300M了都没有断（回复的时候已经下载到快500M了），内存占用也没有上升。

![screenshot](https://cloud.githubusercontent.com/assets/1279432/7555493/0f8b91a6-f745-11e4-8c01-b866556a6fc2.png)

所以我个人猜测可能是在Windows平台出现了内存泄漏。能帮忙测试一下win32是否也有该问题么？

**Comment by ctexlive** [comment]
我截图给你吧。我这次换个电脑测试。

**Comment by librehat** [comment]
这个是只有在做服务端的时候才发生是么？shadowsocks-libqss在Windows下运行为客户端的时候也会这样吃内存吗？

P.S. 你网速好快啊……27.44MB/s

**Comment by ctexlive** [comment]
客户端没问题，高速下载时，ss-qt5的内存占用一直稳定在10MB左右，不会出现中断，CPU 25%左右，完全可以接受。

**Comment by ctexlive** [comment]
没有，我只有最新版的。

在 2015年5月11日 下午6:58，Symeon Huang <notifications@github.com>写道：

**Comment by librehat** [comment]
Version 1.5.1 for win64: https://onedrive.live.com/redir?resid=dc7256aa71a05f51!1793&authkey=!APfUB5LngmKyAnE&ithint=file%2c7z

Please test it, thx.

**Comment by ctexlive** [comment]
测试结果，内存增长比1.6的慢点，客户端下载到1.41GB后服务端挂，此时服务端内存占用涨到~400MB

2015-05-11 20:53 GMT+08:00 Symeon Huang <notifications@github.com>:

**Comment by librehat** [comment]
谢谢，那看起来都不是regression，而是一直就有的问题了。有待研究。

**Comment by Stanlazy-II** [comment]
遇到了一样的问题。。。用ss作为代理使用idm下载http的文件，服务端会在几个小时内把内存占完后就歇菜。。。如果是看视频这种低流速的，内存涨一会儿就会自动掉回去。。。
版本1.11.0，服务端windows server 2012r2，客户端windows server 2016
这问题都两年了呢。。。

**Comment by librehat** [comment]
刚刚我编译了master分支在Windows下做服务器，尝试了下载ISO文件， 网速测试，内存占用没有明显增长（稳定在7MB左右）。请各位测试一下！

[shadowsocks-libqss-2a0d2c1dd784da67dcd88e04dd09d243eabeb3ba-win64.zip](https://github.com/shadowsocks/libQtShadowsocks/files/1324849/shadowsocks-libqss-2a0d2c1dd784da67dcd88e04dd09d243eabeb3ba-win64.zip)

SHA1SUM: fc3518eaff98e0c9c61b5c145d939d2e1f18f7c0

**Comment by Stanlazy-II** [comment]
试了一下。。。这次涨的更猛了，网速20Mbps的时候内存一秒100M左右的速度涨，系统是Windows server 2016
顺便，手机客户端的打开dns通过udp转发以后就无法请求dns

> 刚刚我编译了master分支在Windows下做服务器，尝试了下载ISO文件， 网速测试，内存占用没有明显增长（稳定在7MB左右）。请各位测试一下！
shadowsocks-libqss-2a0d2c1dd784da67dcd88e04dd09d243eabeb3ba-win64.zip
SHA1SUM: fc3518eaff98e0c9c61b5c145d939d2e1f18f7c0

**Comment by Stanlazy-II** [comment]
我似乎知道了内存泄露的一个条件：
如果我通过ss代理下载ss服务端所在机器上的iis里的一个文件，就会疯狂漏内存
如果我通过ss代理下载google drive的文件，内存占用就会保持在20M内

> 试了一下。。。和之前一样的涨，网速20Mbps的时候内存一秒100M左右的速度涨，系统是Windows server 2016
顺便，手机客户端的打开dns通过udp转发以后就无法请求dns

**Comment by librehat** [comment]
Interesting discovery. That still doesn't make much sense to me -_-

**Comment by Stanlazy-II** [comment]
这里是我之前抓的dump，不知道有没有用。。。
https://drive.google.com/file/d/0B1CPDLm4mXCdTVZCZU5Kc0RacU0/view?usp=sharing

**Comment by librehat** [comment]
刚刚我自己测试了一下，2.0.2版做服务端，在Windows 10下此问题无法重现。不知道是不是因为我的网速不够各位的快。。。请各位测试一下

**Comment by librehat** [comment]
Close due to no more feedbacks
