### ISSUE TITLE
Support PAC file

### ISSUE THREAD

**Issue by librehat** [shadowsocks/libQtShadowsocks#48]

**Comment by librehat** [comment]
It needs QtScript to check PAC file, which means more dependency. Put this into low-priority.

**Comment by LazyZhu** [comment]
How about load balance?

**Comment by librehat** [comment]
@LazyZhu TODO #44

**Comment by LazyZhu** [comment]
@librehat Yep, but right now need 3rd app like HAProxy, 3proxy or DeleGate works with ss-qt5 under windows.

**Comment by librehat** [comment]
@LazyZhu Please comment under #44 

that feature is going to be implemented in next major update

**Comment by librehat** [comment]
PAC is delayed to next major update as I was too busy.

**Comment by librehat** [comment]
This won't be done since `QtScript` is deprecated and the replacement `QJSEngine` is a part of `QtDeclarative` (which adds a lot of dependencies and makes the executable on Windows even bigger).

Pull requests using `QJSEngine` might be welcomed and merged.
