### ISSUE TITLE
Got the error message when run this SS Server on my Windows 7

### ISSUE THREAD

**Issue by DaleXiao** [shadowsocks/libQtShadowsocks#54]
Thanks for your hard working!

I got the following error message when running this SS Sever on my Windows 7, I was trying to connect this SS Sever from another windows PC with SS client:

Connecting api.github.com:443 from x.x.x.x:xxxx (x is my server IP and port number)
Remote socket error: Connection timed out

Would you please kindly help me out?

**Comment by librehat** [comment]
Please check your server firewall settings.
