### ISSUE TITLE
Missing botan but botan was installed

### ISSUE THREAD

**Issue by huhu2207** [shadowsocks/libQtShadowsocks#57]
Hi there,

I've tested on my mac with **OSX 10.11.1 + Brew + Botan 1.11.25**，

Firstly I used brew to install the dependencies, which the command was:
```
brew install qt5 zbar botan qrencode
```

Then I started compiling, the **qmake** command is:
```
qmake INSTALL_PREFIX=/usr/local 
```

But when I was running **make**, it shows me this error.
```
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/local/bin/qmake /Users/Jackson/Documents/projects/ss-qt/libQtShadowsocks/lib/libQtShadowsocks.pro INSTALL_PREFIX=/usr/local -o Makefile.libQtShadowsocks ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.libQtShadowsocks 
Info: creating stash file /Users/Jackson/Documents/projects/ss-qt/libQtShadowsocks/lib/.qmake.stash
Project ERROR: botan-1.10 development package not found
```

So I removed the **botan** which installed by **brew** and then re-downloaded one copy from their offical pages, then compiled and installed **botan**. After that I compile again, with specified **qmake INSTALL_PREFIX=/usr/local BORTAN_VER="1.11"**, it shows me the same error:
```
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/local/bin/qmake /Users/Jackson/Documents/projects/ss-qt/libQtShadowsocks/lib/libQtShadowsocks.pro INSTALL_PREFIX=/usr/local  BORTAN_VER=1.11 -o Makefile.libQtShadowsocks ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.libQtShadowsocks 
Info: creating stash file /Users/Jackson/Documents/projects/ss-qt/libQtShadowsocks/lib/.qmake.stash
Project ERROR: botan-1.10 development package not found
```

So what's going on then? Why it still goes with **botan-1.10** but not with **botan-1.11** which I specified in my command? Is it an issue in OSX?

Regards,
Jackson

**Comment by librehat** [comment]
You need to install Botan into your system lib directory. Otherwise, the compiler won't be able to find those files.

Another trick you can do is to install botan into the same directory as the compiler.

I'm not sure why you got the error messages.

**Comment by librehat** [comment]
It's BOTAN not BORTAN

**Comment by huhu2207** [comment]
Yep got it.

BTW sorry for my stupid spelling mistake .

Jackson
