### ISSUE TITLE
Compile error(v1.8.2)

### ISSUE THREAD

**Issue by ykelvis** [shadowsocks/libQtShadowsocks#59]
I'm getting error compiling v1.8.2 on archlinux.

Error log: http://pastebin.com/56JXyTQt

```
build() {
        cd "$srcdir/$_pkgname-$pkgver"
        qmake INSTALL_PREFIX=/usr BOTAN_VER="1.11" DEFINES+="LIB64"
        make
}
```

I thought it may caused by [recent abi change](https://www.archlinux.org/news/c-abi-change/), but v1.8.1 builds fine.

**Comment by librehat** [comment]
It's caused by botan ABI changes.

**Comment by librehat** [comment]
Please use Botan 1.10 where possible. 1.11 is a development branch for their 2.0 release and subject to changes. I don't have time to track their ABI changes before the final release.

The source is built successfully on [Ubuntu Launchpad](https://launchpad.net/~hzwhuang/+archive/ubuntu/ss-qt5).

**Comment by ykelvis** [comment]
With botan 1.10 still got this.
Also, 1.8.1 and any version older can be built successfully. Only 1.8.2 not.
```
/../lib/libQtShadowsocks.so: undefined reference to `Botan::LibraryInitializer::initialize(std::string const&)'
/../lib/libQtShadowsocks.so: undefined reference to `Botan::get_cipher(std::string const&, Botan::OctetString const&, Botan::OctetString const&, Botan::Cipher_Dir)'
/../lib/libQtShadowsocks.so: undefined reference to `Botan::get_cipher(std::string const&, Botan::Cipher_Dir)'
collect2: error: ld returned 1 exit status
Makefile:155: recipe for target 'qss_test' failed
make[1]: *** [qss_test] Error 1
make[1]: Leaving directory '/tmp/git/aur/libqtshadowsocks/src/libQtShadowsocks-1.8.2/test'
Makefile:130: recipe for target 'sub-test-test-pro-make_first-ordered' failed
make: *** [sub-test-test-pro-make_first-ordered] Error 2
```

**Comment by librehat** [comment]
The diff between `1.8.2` and `1.8.1` is minor and doesn't touch anything related to `botan`.

Besides, `1.8.2` can be built successfully on all supported Fedora and Ubuntu versions. This issue should be related to `botan` or Arch's ABI breaks
