### ISSUE TITLE
some errors when i exec ‘make’ in 1.8.4

### ISSUE THREAD

**Issue by heshunwq** [shadowsocks/libQtShadowsocks#66]
I don‘t know c++ ......

cd lib/ && make -f Makefile.libQtShadowsocks 
make[1]: Entering directory '/home/heshun/DEV/Tools/Shadowsocks/libQtShadowsocks-1.8.0/lib'
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQSS_VERSION=\"1.8.0\" -DQSS_LIBRARY -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I/usr/include/botan-1.10 -I. -o address.o address.cpp
In file included from common.h:30:0,
                 from address.cpp:25:
address.h:44:21: error: expected ‘,’ or ‘...’ before ‘&&’ token
     Address(Address &&) = default;//force the generation of default mov
                     ^
address.h:44:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
     Address(Address &&) = default;//force the generation of default mov
                           ^
address.h:44:27: error: invalid constructor; you probably meant ‘QSS::Address (const QSS::Address&)’
Makefile.libQtShadowsocks:379: recipe for target 'address.o' failed
make[1]: *** [address.o] Error 1
make[1]: Leaving directory '/home/heshun/DEV/Tools/Shadowsocks/libQtShadowsocks-1.8.0/lib'
Makefile:40: recipe for target 'sub-lib-libQtShadowsocks-pro-make_default-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_default-ordered] Error 2

**Comment by librehat** [comment]
Please install Qt 5. You're using Qt 4
