### ISSUE TITLE
make error(opensuse 42.1)

### ISSUE THREAD

**Issue by sify21** [shadowsocks/libQtShadowsocks#67]
I'm using opensuse 42.1, I try to install ver1.8.4 by compiling, but I get this error when i run make:

In file included from common.h:30:0, 
from address.cpp:25:
address.h:51:21: error: expected ‘,’ or ‘...’ before ‘&&’ token
&emsp;&emsp;Address(Address &&) = default;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;^
address.h:51:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
&emsp;&emsp;Address(Address &&) = default;
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;^
address.h:51:27: error: invalid constructor; you probably meant ‘QSS::Address (const QSS::Address&)’
Makefile.libQtShadowsocks:376: recipe for target 'address.o' failed

I tried to add arguments to qmake, and tried other version(1.8.0), but I still get this error. I don't know what's wrong.

**Comment by librehat** [comment]
Are you sure you're using Qt 5?
And it seems your compiler doesn't support C++11
