### ISSUE TITLE
谷歌商店还是几乎不能下载?

### ISSUE THREAD

**Issue by hehehym** [shadowsocks/libQtShadowsocks#69]
之前几个月的版本INS的图片不能读取,商店的东西不能下载,现在新版本ins之类的社交软件图片可以读取出来了,但是商店下东西几乎是下不动,一点下载,开始的几秒钟有速度,然后就没速度了,要过几分钟,甚至10几分钟才会重新恢复速度,然后也只是持续几秒钟,如此循环,一个几十M的东西要下一个小时,我不知道是不是自己的问题,所以同一个VPS里我又装了libev的ss来测试一下,发现配置文件一样的情况下~libqtss商店下东西如上所说,但是libev是正常持续下载状态~
  然后今天外出有事用了一下谷歌地图导航~发现也是影响很大,这一秒钟定位到这里,然后要开几百米,或者几公里导航才会有反应,情况就像是商店下东西的情况似的.我也不知道是不是真的是我个人的问题,所以想问清楚一下~麻烦啦~  -_-!!

**Comment by librehat** [comment]
#42
