### ISSUE TITLE
Could not find a thread-safe mutex object to use and method not supproted.

### ISSUE THREAD

**Issue by aydenlin** [shadowsocks/libQtShadowsocks#73]
libQtshadowsocks-1.8.4和ss-qt5都出现了这个问题

Could not find a thread-safe mutex object to use
Initialising ciphers...
The method  is not supported.
Initialisation failed.
Controller is not valid. Maybe improper setup?

系统Gentoo-4.1.12

qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib64/qt4

botan version 1.10.5

gcc -v 

Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.3/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.9.3/work/gcc-4.9.3/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.3/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.9.3/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 4.9.3 p1.4, pie-0.6.4' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --disable-libcilkrts --enable-lto --without-cloog --enable-libsanitizer
Thread model: posix
gcc version 4.9.3 (Gentoo 4.9.3 p1.4, pie-0.6.4)

**Comment by librehat** [comment]
It requires Qt5. qmake-qt5 --version?

**Comment by aydenlin** [comment]
I have installed both qt4 and qt5, and i used /usr/bin/qt5/bin/qmake to make the Makefile,,

qmake-qt5 --version

/usr/lib/qt5/bin/qmake -v
QMake version 3.0
Using Qt version 5.4.2 in /usr/lib64

**Comment by aydenlin** [comment]
head of the Makefile in the root of libQtShadowsocks-1.8.4
  1 ##################################################################    
  2 # Makefile for building: QtShadowsocks
  3 # Generated by qmake (3.0) (Qt 5.4.2)
  4 # Project:  QtShadowsocks.pro
  5 # Template: subdirs
  6 # Command: /usr/lib/qt5/bin/qmake -o Makefile QtShadowsocks.pro
  7 ################################################################## 

Makefile in lib dir
  1 #############################################################################
  2 # Makefile for building: libQtShadowsocks.so.1.8.4
  3 # Generated by qmake (3.0) (Qt 5.4.2)
  4 # Project:  libQtShadowsocks.pro
  5 # Template: lib
  6 # Command: /usr/lib/qt5/bin/qmake -o Makefile.libQtShadowsocks libQtShadowsocks.pro
  7 ###########################################################

and something i found ,  seems "Could not find a thread-safe mutex object to use" is throw by
botan but i don't know what is it and how to deal with.

#if defined(BOTAN_HAS_MUTEX_PTHREAD)    
  mutex_factory = new Pthread_Mutex_Factory;
#elif defined(BOTAN_HAS_MUTEX_WIN32)
      mutex_factory = new Win32_Mutex_Factory;
#elif defined(BOTAN_HAS_MUTEX_QT)
      mutex_factory Qt_Mutex_Factory;
#else
      throw Invalid_State("Could not find a thread-safe mutex object to use");
#endif

**Comment by librehat** [comment]
You need to recompile botan and make sure it has mutex support. I suggest you to check it on Gentoo
