### ISSUE TITLE
在电脑上透过SS下载东西服务端会崩溃.

### ISSUE THREAD

**Issue by hehehym** [shadowsocks/libQtShadowsocks#76]
不知道和在PLAY STORE是不是同一个原因造成的~但是遇到了就和作者说一下..
在电脑上全局SS,(客户端SSqt5,系统win10 64bit,服务端libSS)下载东西,一下载过两秒,vps的服务端的进程会被杀死.导致SS链接中断.
试过一下用libev的服务端(客户端系统等因素相同),SS全局下下载东西正常.

**Comment by librehat** [comment]
win版有内存泄漏的问题，估计是内存占用暴涨被杀死。见已开的相关问题。
