### ISSUE TITLE
这个有办法最小化在后台运行吗?

### ISSUE THREAD

**Issue by OtaMegane** [shadowsocks/libQtShadowsocks#82]
这个有办法最小化在后台运行吗?

**Comment by librehat** [comment]
Windows no. 
Linux yes.

**Comment by zhensss** [comment]
可以隐藏噢···比如：
使用这种.VBS的方式来运行你的bat脚本
Set ws = CreateObject("Wscript.Shell")
ws.run "cmd /c ss.bat",vbhide
