### ISSUE TITLE
botan-1.10 development package not found

### ISSUE THREAD

**Issue by laoluan** [shadowsocks/libQtShadowsocks#83]
english:
when i use "make" command,here have been some mistakes，“libbotan1.10-dev ”It has been installed，Great God, please help me!!
中文：我在使用make命令编译libQtShadowsocks的时候提示以下错误，botan-1.10没安装，可是我装的已经是最新版本，求大神帮忙啊！！

cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/yanhan/libQtShadowsocks/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks 
Project ERROR: botan-1.10 development package not found
Makefile:44: recipe for target 'sub-lib-libQtShadowsocks-pro-make_first-ordered' failed
make: **\* [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 3

**Comment by librehat** [comment]
你什么操作系统/发行版？你确定你安装了`libbotan1.10-dev`？

**Comment by SmallGress** [comment]
osx 10.11.5...同样报这个错误...提示botan 没找到


cd lib/ && /usr/local/bin/qmake /Users/gress/Desktop/soft/ss/libQtShadowsocks/lib/libQtShadowsocks.pro INSTALL_PREFIX=/usr/local -o Makefile.libQtShadowsocks
sh: pkg-config: command not found
Project ERROR: Package botan-1.10 not found
make: *** [lib/Makefile.libQtShadowsocks] Error 2

**Comment by wallena3** [comment]
遇到同样问题  确定已安装libbotan1.10-dev

**Comment by librehat** [comment]
Please post your OS/Linux distribution and version!

**Comment by zgbkdlm** [comment]
我也遇见这样的问题了， debian/jessie 8.5.0 stable，已经安转了libbotan了，

**Comment by zgbkdlm** [comment]
换了两家VPS试了下，也是和本机同样的问题
root@debian:~/libQtShadowsocks-1.9.0# ls
debian	lib  LICENSE  QtShadowsocks.pro  README.md  shadowsocks-libqss	test
root@debian:~/libQtShadowsocks-1.9.0# qmake
root@debian:~/libQtShadowsocks-1.9.0# make
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /root/libQtShadowsocks-1.9.0/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks 
Project ERROR: botan-1.10 development package not found
Makefile:40: recipe for target 'sub-lib-libQtShadowsocks-pro-make_first-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 3

**Comment by librehat** [comment]
`apt-cache search libbotan-dev`?
You need `libbotan-dev` too. Not just `libbotan`

**Comment by shensl** [comment]
sudo apt-get install libbotan1.10-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
libbotan1.10-dev 已经是最新的版本。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
=========================================================
qmake&&make
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /tmp/tmp/libQtShadowsocks/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks 
Project ERROR: botan-1.10 development package not found
Makefile:40: recipe for target 'sub-lib-libQtShadowsocks-pro-make_first-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 3

**Comment by ParadiseDS** [comment]
osx 10.12.1 同样出现了这个问题
看之前的 #75 貌似已经修复了问题，但是我 checkout 到那个修复提交依然提示同样的错误
以及楼上apt的包brew下面并不清楚对应的那些_(:з」∠)_

**Comment by wukhai** [comment]
osx 10.10.1  同样出现此问题
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/local/bin/qmake /Users/wukhai/work/qlicom/shadowsocks/libQtShadowsocks/lib/libQtShadowsocks.pro -spec macx-clang CONFIG+=x86_64 INSTALL_PREFIX=/usr/local -o Makefile.libQtShadowsocks ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.libQtShadowsocks clean
/usr/local/bin/qmake -spec macx-clang CONFIG+=x86_64 INSTALL_PREFIX=/usr/local -o Makefile.libQtShadowsocks libQtShadowsocks.pro
Project ERROR: botan-1.10 development package not found

**Comment by wukhai** [comment]
有谁解决了这个问题，麻烦把解决方法贴上来，谢谢

**Comment by librehat** [comment]
macOS: https://github.com/shadowsocks/libQtShadowsocks/wiki/Compiling#building-on-mac-os-x

**Comment by ParadiseDS** [comment]
@librehat wiki页面上的内容和之前貌似是一致的，也没有新的提交，为什么关闭了 issue。。。osx 10.12.1 依然没有找到解决这个问题的办法

**Comment by josephzjw** [comment]
I tried the method of @shensl and it works... Thanks

**Comment by 0es** [comment]
@shensl 的方法解决了问题。感谢

**Comment by AverageJoeWang** [comment]
when I installed botan and Qt5 with command line, I found that the version of botan is about 2.1.0, so I  use 

qmake INSTALL_PREFIX=/usr/local BOTAN_VER="2"
make all
make install

it works.

**Comment by jefferyship** [comment]
how can i install libbotan1.10-dev on mac ?
