### ISSUE TITLE
shadowsocks-libqss compiling error

### ISSUE THREAD

**Issue by flyc** [shadowsocks/libQtShadowsocks#84]
hi, i meet an link error while i complie the shadowsocks-libqss.
`mingw32-make[1]: Entering directory 'F:/ss/sock5/libQtShadowsocks-master/build-QtShadowsocks-Desktop_Qt_5_7_0_MinGW_32bit-Release/shadowsocks-libqss'
g++ -Wl,-s -Wl,-subsystem,console -mthreads -o release\shadowsocks-libqss.exe release/client.o release/main.o release/utils.o release/moc_client.o  -LF:\ss\sock5\libQtShadowsocks-master\libQtShadowsocks-master\botan\lib -L..\lib\release -L..\lib -lQtShadowsocks -lbotan-1.10 -LC:\Qt\5.7\mingw53_32\lib C:\Qt\5.7\mingw53_32\lib\libQt5Network.a C:\Qt\5.7\mingw53_32\lib\libQt5Core.a 
..\lib\release/libQtShadowsocks.a(controller.o):controller.cpp:(.text+0x11c4): undefined reference to `Botan::LibraryInitializer::initialize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
..\lib\release/libQtShadowsocks.a(cipher.o):cipher.cpp:(.text+0x467): undefined reference to `Botan::get_cipher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Botan::Cipher_Dir)'
..\lib\release/libQtShadowsocks.a(cipher.o):cipher.cpp:(.text+0x8b7): undefined reference to `Botan::get_cipher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Botan::OctetString const&, Botan::OctetString const&, Botan::Cipher_Dir)'
collect2.exe: error: ld returned 1 exit status
Makefile.Release:69: recipe for target 'release\shadowsocks-libqss.exe' failed`

win10+mingw-32+qt creater
botan-1.10.9, `configure.py --cc=gcc --os=mingw --with-tr1=none --cpu=x86_32 --disable-shared --disable-debug`
thx so much

**Comment by librehat** [comment]
You need to install Botan into Qt's directory. It seems the linker can't find botan library. Alternatively, you can modify project file to add botan into library path.

**Comment by flyc** [comment]
thanks fo reply,  i already add botan into libray path in project file( shadowsock-libqss.pro) like this:

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../botan/lib/ -lbotan-1.10
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../botan/lib/ -lbotan-1.10d
INCLUDEPATH += $$PWD/../botan/include
DEPENDPATH += $$PWD/../botan/include

if the botan lib path is wrong, the linker will tell me "error: cannot find -lbotan-1.10".  the linker can't find this two function 'initialize(*), get_cipher(*), 
It's wrong botan version(1.10.9) i use?

**Comment by librehat** [comment]
Sometimes the library linking order also matters. `-lbotan-1.10` should already be in the project file.

This undefined reference is a linking error. 1.10.x are all compatible as long as you compile the code against the same version of botan.

**Comment by flyc** [comment]
yeah, 1.10,x are all compatible. 
win10 + visual studio 2015(compiler:cl)  + botan(1.10.9 static lib) + qt(5.7.0 static), everything is ok now, 
i think it's closed, thanks so much @librehat
