### ISSUE TITLE
win2008  libQtShadowsocks  Can't support 'auth_sha1' and 'http_simple'?

### ISSUE THREAD

**Issue by lyq8201818** [shadowsocks/libQtShadowsocks#87]
win2008  libQtShadowsocks  Can't support 'auth_sha1' and 'http_simple'?
Could you support ?, thank you for helping me

**Comment by lyq8201818** [comment]
请问这个版本的如何开启 SHA1协议 和 混傲模式啊

**Comment by librehat** [comment]
Doesnt' support by design
