### ISSUE TITLE
install  Error  centos 7x86_64

### ISSUE THREAD

**Issue by zinian** [shadowsocks/libQtShadowsocks#88]
yum install libQtShadowsocks
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * extras: mirror.team-cymru.org
 * updates: linux.mirrors.es.net
Resolving Dependencies
--> Running transaction check
---> Package libQtShadowsocks.x86_64 0:1.9.0-3.el7.centos will be installed
--> Processing Dependency: qt5-qtbase for package: libQtShadowsocks-1.9.0-3.el7.centos.x86_64
--> Processing Dependency: botan for package: libQtShadowsocks-1.9.0-3.el7.centos.x86_64
--> Finished Dependency Resolution

Error: Package: libQtShadowsocks-1.9.0-3.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: botan

Error: Package: libQtShadowsocks-1.9.0-3.el7.centos.x86_64 (librehat-shadowsocks)
           Requires: qt5-qtbase

 You could try using --skip-broken to work around the problem

 You could try running: rpm -Va --nofiles --nodigest

**Comment by librehat** [comment]
You need to install EPEL repo
