### ISSUE TITLE
error with dpkg-buildpackage -uc -us -b

### ISSUE THREAD

**Issue by lihaooahil** [shadowsocks/libQtShadowsocks#89]
Debian: Deepin 15.2 jessie
I try the command sudo dpkg-buildpackage -uc -us -b
but I can not get libqtshadowsocks and shadowsocks-libqtshadowsocks deb packages 
because the following error comes out:
dpkg-buildpackage: info: source package libqtshadowsocks
dpkg-buildpackage: info: source version 1.9.0-1
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by Symeon Huang <hzwhuang@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build libQtShadowsocks-master
 debian/rules clean
dh clean --parallel
   dh_testdir
   dh_auto_clean
	make -j1 distclean
make[1]: Entering directory '/home/li/下载/libQtShadowsocks-master'
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/li/下载/libQtShadowsocks-master/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks distclean
make[2]: Entering directory '/home/li/下载/libQtShadowsocks-master/lib'
rm -f moc_address.cpp moc_addresstester.cpp moc_chacha.cpp moc_cipher.cpp moc_controller.cpp moc_encryptor.cpp moc_encryptorprivate.cpp moc_rc4.cpp moc_tcprelay.cpp moc_udprelay.cpp moc_httpproxy.cpp moc_socketstream.cpp moc_tcpserver.cpp
rm -f address.o addresstester.o chacha.o cipher.o common.o controller.o encryptor.o encryptorprivate.o rc4.o tcprelay.o udprelay.o httpproxy.o socketstream.o tcpserver.o profile.o moc_address.o moc_addresstester.o moc_chacha.o moc_cipher.o moc_controller.o moc_encryptor.o moc_encryptorprivate.o moc_rc4.o moc_tcprelay.o moc_udprelay.o moc_httpproxy.o moc_socketstream.o moc_tcpserver.o
rm -f *~ core *.core
rm -f libQtShadowsocks.so.1.9.0 
rm -f libQtShadowsocks.so libQtShadowsocks.so.1 libQtShadowsocks.so.1.9 libQtShadowsocks.a
rm -f libQtShadowsocks.prl pkgconfig/QtShadowsocks.pc
rm -f Makefile.libQtShadowsocks
make[2]: Leaving directory '/home/li/下载/libQtShadowsocks-master/lib'
cd shadowsocks-libqss/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/li/下载/libQtShadowsocks-master/shadowsocks-libqss/shadowsocks-libqss.pro -o Makefile ) && make -f Makefile distclean
make[2]: Entering directory '/home/li/下载/libQtShadowsocks-master/shadowsocks-libqss'
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile shadowsocks-libqss.pro
rm -f moc_client.cpp
rm -f client.o main.o utils.o moc_client.o
rm -f *~ core *.core
rm -f shadowsocks-libqss 
rm -f Makefile
make[2]: Leaving directory '/home/li/下载/libQtShadowsocks-master/shadowsocks-libqss'
cd test/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/li/下载/libQtShadowsocks-master/test/test.pro -o Makefile ) && make -f Makefile distclean
make[2]: Entering directory '/home/li/下载/libQtShadowsocks-master/test'
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile test.pro
rm -f moc_address.t.cpp moc_chacha.t.cpp moc_cipher.t.cpp moc_profile.t.cpp
rm -f main.o address.t.o chacha.t.o cipher.t.o profile.t.o moc_address.t.o moc_chacha.t.o moc_cipher.t.o moc_profile.t.o
rm -f *~ core *.core
rm -f qss_test 
rm -f Makefile
make[2]: Leaving directory '/home/li/下载/libQtShadowsocks-master/test'
rm -f Makefile
make[1]: Leaving directory '/home/li/下载/libQtShadowsocks-master'
   dh_clean
 debian/rules build
dh build --parallel
   dh_testdir
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/li/下载/libQtShadowsocks-master'
qmake
make[1]: Leaving directory '/home/li/下载/libQtShadowsocks-master'
   dh_auto_build
	make -j1
make[1]: Entering directory '/home/li/下载/libQtShadowsocks-master'
cd lib/ && ( test -e Makefile.libQtShadowsocks || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/li/下载/libQtShadowsocks-master/lib/libQtShadowsocks.pro -o Makefile.libQtShadowsocks ) && make -f Makefile.libQtShadowsocks 
make[2]: Entering directory '/home/li/下载/libQtShadowsocks-master/lib'
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQSS_VERSION=\"1.9.0\" -DQSS_LIBRARY -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/botan-1.10 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o address.o address.cpp
make[2]: g++: Command not found
Makefile.libQtShadowsocks:459: recipe for target 'address.o' failed
make[2]: *** [address.o] Error 127
make[2]: Leaving directory '/home/li/下载/libQtShadowsocks-master/lib'
Makefile:44: recipe for target 'sub-lib-libQtShadowsocks-pro-make_first-ordered' failed
make[1]: *** [sub-lib-libQtShadowsocks-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/home/li/下载/libQtShadowsocks-master'
dh_auto_build: make -j1 returned exit code 2
debian/rules:6: recipe for target 'build' failed
make: *** [build] Error 25
dpkg-buildpackage: error: debian/rules build gave error exit status 2

can anyone help? Thanks.

**Comment by librehat** [comment]
```
make[2]: g++: Command not found
```
You don't even have essential build tools. (C++ compiler)
