### ISSUE TITLE
how did you do the cipher speed comparison?

### ISSUE THREAD

**Issue by enihcam** [shadowsocks/libQtShadowsocks#91]
how did you do the cipher speed comparison? Did you enable AES hardware capability in i5-6500U? Hardware AES should be faster than salsa20/chacha20.

**Comment by librehat** [comment]
It depends on how `botan` library was built. And I believe AES hardware is enabled that's why it's so fast on modern CPU chips.

Check `shadowsocks-libqss` for speed test

**Comment by enihcam** [comment]
I don't think the AES hardware is enabled in test scenario, otherwise how come AES is still slower than chacha20/salsa20?
