### ISSUE TITLE
win7  编译时提示 \cipher.h:35: error: botan/pipe.h: No such file or directory  #include <botan/pipe.h>

### ISSUE THREAD

**Issue by phoenixylf** [shadowsocks/libQtShadowsocks#94]
G:\qt-workspace\ss\libQtShadowsocks-master\lib\cipher.h:35: error: botan/pipe.h: No such file or directory
 #include <botan/pipe.h>
 
已经编译了botan1.0版本的   并将路径包含在了.pro文件里面   但还是编译不过。

包含头文件代码如下：

win32: LIBS += -L$$PWD/../botan/ -lbotan

INCLUDEPATH += $$PWD/../botan/include
DEPENDPATH += $$PWD/../botan/include

**Comment by librehat** [comment]
自己检查一下，肯定是没有找到botan的头文件。你可以试着直接复制粘贴到Qt的include里
