### ISSUE TITLE
编译不了阿 cant complie this lib....

### ISSUE THREAD

**Issue by devil1995** [shadowsocks/libQtShadowsocks#99]
报错如此下（issue is below ）：
不知道怎弄，gCC 4.8...botan 编译安装1.11 ...opensuse 42.1

I Dont know what happend ...the GCC is 4.8 and the botan is already installed and its version is 1.11...opensuse 42.0 leaps...Can anyone tell me why it cant be complied >?>code error ???it not seems like that .the error information is below...

In file included from common.h:30:0,
                 from address.cpp:25:
address.h:51:21: error: expected ‘,’ or ‘...’ before ‘&&’ token
     Address(Address &&) = default;
                     ^
address.h:51:27: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     Address(Address &&) = default;
                           ^
address.h:51:27: error: invalid constructor; you probably meant ‘QSS::Address (const QSS::Address&)’
Makefile.libQtShadowsocks:378: recipe for target 'address.o' failed
make[1]: *** [address.o] Error 1
make[1]: Leaving directory '/home/devil/ss/libqt5/libQtShadowsocks-master/lib'
Makefile:41: recipe for target 'sub-lib-libQtShadowsocks-pro-make_default-ordered' failed
make: *** [sub-lib-libQtShadowsocks-pro-make_default-ordered] Error 2

**Comment by devil1995** [comment]
I have tried two versions of this lib ....and my linux have no the binary to install directly ...so sad that can't use my linux to visit internet outside

**Comment by librehat** [comment]
Try to use `qmake-qt5` not `qmake`
